import AppKit
import Foundation

/// Decides what must never be recorded.
///
/// `org.nspasteboard.ConcealedType` is the convention password managers
/// (1Password, Bitwarden, Keychain Access, KeePassXC) set on copied credentials.
/// `TransientType` and `AutoGeneratedType` mark values an app put on the
/// pasteboard programmatically that were never meant to outlive the moment.
/// Honouring these is the entire reason the convention exists — see
/// http://nspasteboard.org
///
/// Checked *before* anything reads the contents, so a concealed value is never
/// held in memory, never hashed, and never reaches the disk.
enum PasteboardPrivacy {

    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Set by older 1Password versions, which predate the convention.
        "com.agilebits.onepassword",
    ]

    /// Takes plain strings rather than an `NSPasteboard` so the rule can be
    /// tested without one.
    static func isConcealedOrTransient(types: [String]) -> Bool {
        types.contains { excludedTypes.contains($0) }
    }

    static func isConcealedOrTransient(_ pasteboard: NSPasteboard) -> Bool {
        isConcealedOrTransient(types: (pasteboard.types ?? []).map(\.rawValue))
    }

    /// The full test, including apps the user has chosen to exclude.
    ///
    /// A bundle identifier rather than a name: an app the user excluded should
    /// stay excluded when it is renamed or localised.
    static func shouldIgnore(
        types: [String],
        sourceBundleID: String?,
        excludedBundleIDs: Set<String> = []
    ) -> Bool {
        if isConcealedOrTransient(types: types) { return true }
        if let sourceBundleID, excludedBundleIDs.contains(sourceBundleID) { return true }
        return false
    }
}
