import Testing

@testable import Copas

struct PasteboardPrivacyTests {

    @Test(arguments: [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ])
    func markedPasteboardsAreRefused(marker: String) {
        #expect(PasteboardPrivacy.isConcealedOrTransient(types: ["public.utf8-plain-text", marker]))
    }

    @Test func anOrdinaryCopyIsAllowed() {
        #expect(!PasteboardPrivacy.isConcealedOrTransient(types: ["public.utf8-plain-text", "public.rtf"]))
        #expect(!PasteboardPrivacy.isConcealedOrTransient(types: []))
    }

    /// Excluding by bundle identifier rather than by name, so an app stays
    /// excluded when it is renamed or its name is localised.
    @Test func appsTheUserExcludedAreRefused() {
        #expect(PasteboardPrivacy.shouldIgnore(
            types: ["public.utf8-plain-text"],
            sourceBundleID: "com.1password.1password",
            excludedBundleIDs: ["com.1password.1password"]
        ))
        #expect(!PasteboardPrivacy.shouldIgnore(
            types: ["public.utf8-plain-text"],
            sourceBundleID: "com.apple.Safari",
            excludedBundleIDs: ["com.1password.1password"]
        ))
    }

    @Test func anUnknownSourceIsNotExcludedByAccident() {
        #expect(!PasteboardPrivacy.shouldIgnore(
            types: ["public.utf8-plain-text"],
            sourceBundleID: nil,
            excludedBundleIDs: ["com.1password.1password"]
        ))
    }
}
